export interface TLDPrice {
    TLD: string;
    PriceRegistration: number;
    PriceChangeOwnership: number;
    PriceRestoration: number | null;
    PriceTransfer: number | null;
    TransferTerm: "No change" | "Renewed with transfer" | "Not supported";
}
const tldTable: TLDPrice[] = [
    {
        TLD: "ac",
        PriceRegistration: 48.0,
        PriceChangeOwnership: 48.0,
        PriceRestoration: 48.0,
        PriceTransfer: 0.0,
        TransferTerm: "No change",
    },
    {
        TLD: "academy",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "accountants",
        PriceRegistration: 94.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 145.0,
        PriceTransfer: 94.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "adult",
        PriceRegistration: 100.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 160.0,
        PriceTransfer: 100.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "agency",
        PriceRegistration: 19.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 19.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "apartments",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "associates",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "auction",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "audio",
        PriceRegistration: 13.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: null,
        PriceTransfer: null,
        TransferTerm: "Not supported",
    },
    {
        TLD: "band",
        PriceRegistration: 22.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 76.0,
        PriceTransfer: 22.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "bargains",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "be",
        PriceRegistration: 9.0,
        PriceChangeOwnership: 9.0,
        PriceRestoration: 19.0,
        PriceTransfer: 9.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "berlin",
        PriceRegistration: 52.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 235.0,
        PriceTransfer: 52.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "bike",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "bingo",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "biz",
        PriceRegistration: 16.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 72.0,
        PriceTransfer: 16.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "black",
        PriceRegistration: 43.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 96.0,
        PriceTransfer: 43.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "blue",
        PriceRegistration: 15.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 69.0,
        PriceTransfer: 15.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "boutique",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "builders",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "business",
        PriceRegistration: 18.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 62.0,
        PriceTransfer: 18.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "buzz",
        PriceRegistration: 37.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 89.0,
        PriceTransfer: 37.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "ca",
        PriceRegistration: 13.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 13.0,
        PriceTransfer: 13.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "cab",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "cafe",
        PriceRegistration: 31.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 89.0,
        PriceTransfer: 31.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "camera",
        PriceRegistration: 46.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 46.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "camp",
        PriceRegistration: 46.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 46.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "capital",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "cards",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "care",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "careers",
        PriceRegistration: 35.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 35.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "cash",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "casino",
        PriceRegistration: 141.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 190.0,
        PriceTransfer: 141.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "catering",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "cc",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 66.0,
        PriceTransfer: 12.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "center",
        PriceRegistration: 21.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 21.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "ceo",
        PriceRegistration: 74.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 151.0,
        PriceTransfer: 74.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "ch",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 12.0,
        PriceTransfer: 0.0,
        TransferTerm: "No change",
    },
    {
        TLD: "chat",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "cheap",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "church",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "city",
        PriceRegistration: 19.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 19.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "cl",
        PriceRegistration: 93.0,
        PriceChangeOwnership: 93.0,
        PriceRestoration: null,
        PriceTransfer: null,
        TransferTerm: "Not supported",
    },
    {
        TLD: "cloud",
        PriceRegistration: 23.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 82.0,
        PriceTransfer: 23.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "claims",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "cleaning",
        PriceRegistration: 46.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 46.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "click",
        PriceRegistration: 5.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 48.0,
        PriceTransfer: 10.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "clinic",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "clothing",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "club",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 66.0,
        PriceTransfer: 12.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "co",
        PriceRegistration: 25.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 62.0,
        PriceTransfer: 25.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "co.nz",
        PriceRegistration: 24.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 24.0,
        PriceTransfer: 24.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "co.uk",
        PriceRegistration: 9.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 9.0,
        PriceTransfer: 0.0,
        TransferTerm: "No change",
    },
    {
        TLD: "co.za",
        PriceRegistration: 13.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 13.0,
        PriceTransfer: 0.0,
        TransferTerm: "No change",
    },
    {
        TLD: "coach",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "codes",
        PriceRegistration: 35.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 35.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "coffee",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "college",
        PriceRegistration: 69.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 436.0,
        PriceTransfer: 69.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "com",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 66.0,
        PriceTransfer: 12.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "com.ar",
        PriceRegistration: 76.0,
        PriceChangeOwnership: 76.0,
        PriceRestoration: null,
        PriceTransfer: null,
        TransferTerm: "Not supported",
    },
    {
        TLD: "com.au",
        PriceRegistration: 15.0,
        PriceChangeOwnership: 40.0,
        PriceRestoration: 15.0,
        PriceTransfer: 0.0,
        TransferTerm: "No change",
    },
    {
        TLD: "com.br",
        PriceRegistration: 58.0,
        PriceChangeOwnership: 58.0,
        PriceRestoration: null,
        PriceTransfer: null,
        TransferTerm: "Not supported",
    },
    {
        TLD: "com.mx",
        PriceRegistration: 34.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 67.0,
        PriceTransfer: 34.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "com.sg",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 47.0,
        PriceRestoration: null,
        PriceTransfer: null,
        TransferTerm: "Not supported",
    },
    {
        TLD: "community",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "company",
        PriceRegistration: 18.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 62.0,
        PriceTransfer: 18.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "computer",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "condos",
        PriceRegistration: 49.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 49.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "construction",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "consulting",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "contractors",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "cool",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "coupons",
        PriceRegistration: 51.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 108.0,
        PriceTransfer: 51.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "credit",
        PriceRegistration: 94.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 145.0,
        PriceTransfer: 94.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "creditcard",
        PriceRegistration: 141.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 190.0,
        PriceTransfer: 141.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "cruises",
        PriceRegistration: 49.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 49.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "dance",
        PriceRegistration: 22.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 76.0,
        PriceTransfer: 22.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "dating",
        PriceRegistration: 49.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 49.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "de",
        PriceRegistration: 9.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 9.0,
        PriceTransfer: 9.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "deals",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "delivery",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "democrat",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "dental",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "diamonds",
        PriceRegistration: 35.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 35.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "diet",
        PriceRegistration: 19.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: null,
        PriceTransfer: null,
        TransferTerm: "Not supported",
    },
    {
        TLD: "digital",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "direct",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "directory",
        PriceRegistration: 21.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 21.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "discount",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "dog",
        PriceRegistration: 46.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 46.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "domains",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "education",
        PriceRegistration: 21.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 21.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "email",
        PriceRegistration: 25.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 25.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "energy",
        PriceRegistration: 94.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 145.0,
        PriceTransfer: 94.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "engineering",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "enterprises",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "equipment",
        PriceRegistration: 21.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 79.0,
        PriceTransfer: 21.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "es",
        PriceRegistration: 10.0,
        PriceChangeOwnership: 10.0,
        PriceRestoration: 10.0,
        PriceTransfer: 0.0,
        TransferTerm: "No change",
    },
    {
        TLD: "estate",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "eu",
        PriceRegistration: 13.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 13.0,
        PriceTransfer: 13.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "events",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "exchange",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "expert",
        PriceRegistration: 49.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 49.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "exposed",
        PriceRegistration: 19.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 19.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "express",
        PriceRegistration: 31.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 89.0,
        PriceTransfer: 31.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "fail",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "farm",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "fi",
        PriceRegistration: 24.0,
        PriceChangeOwnership: 24.0,
        PriceRestoration: 24.0,
        PriceTransfer: 24.0,
        TransferTerm: "No change",
    },
    {
        TLD: "finance",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "financial",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "fish",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "fitness",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "flights",
        PriceRegistration: 49.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 49.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "florist",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "flowers",
        PriceRegistration: 25.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 66.0,
        PriceTransfer: 25.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "fm",
        PriceRegistration: 92.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 123.0,
        PriceTransfer: 92.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "football",
        PriceRegistration: 19.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 19.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "forsale",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "foundation",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "fr",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 12.0,
        PriceRestoration: 12.0,
        PriceTransfer: 12.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "fund",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "furniture",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "futbol",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 66.0,
        PriceTransfer: 12.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "fyi",
        PriceRegistration: 20.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 79.0,
        PriceTransfer: 20.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "gallery",
        PriceRegistration: 21.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 21.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "gg",
        PriceRegistration: 75.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 91.0,
        PriceTransfer: 75.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "gift",
        PriceRegistration: 20.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 60.0,
        PriceTransfer: 20.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "gifts",
        PriceRegistration: 19.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 19.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "glass",
        PriceRegistration: 46.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 46.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "global",
        PriceRegistration: 71.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 205.0,
        PriceTransfer: 71.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "gold",
        PriceRegistration: 101.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 157.0,
        PriceTransfer: 101.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "golf",
        PriceRegistration: 51.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 108.0,
        PriceTransfer: 51.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "graphics",
        PriceRegistration: 21.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 21.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "gratis",
        PriceRegistration: 19.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 19.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "green",
        PriceRegistration: 71.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 124.0,
        PriceTransfer: 71.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "gripe",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "guide",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "guitars",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: null,
        PriceTransfer: null,
        TransferTerm: "Not supported",
    },
    {
        TLD: "guru",
        PriceRegistration: 25.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 25.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "haus",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "healthcare",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "help",
        PriceRegistration: 16.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 60.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "hiv",
        PriceRegistration: 254.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 300.0,
        PriceTransfer: 254.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "hockey",
        PriceRegistration: 51.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 108.0,
        PriceTransfer: 51.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "holdings",
        PriceRegistration: 35.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 35.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "holiday",
        PriceRegistration: 35.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 35.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "host",
        PriceRegistration: 93.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 201.0,
        PriceTransfer: 93.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "hosting",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: null,
        PriceTransfer: null,
        TransferTerm: "Not supported",
    },
    {
        TLD: "house",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "im",
        PriceRegistration: 19.0,
        PriceChangeOwnership: 19.0,
        PriceRestoration: 19.0,
        PriceTransfer: 0.0,
        TransferTerm: "No change",
    },
    {
        TLD: "immo",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "immobilien",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "in",
        PriceRegistration: 15.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 26.0,
        PriceTransfer: 15.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "industries",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "info",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 70.0,
        PriceTransfer: 12.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "ink",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 88.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "institute",
        PriceRegistration: 21.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 21.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "insure",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "international",
        PriceRegistration: 21.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 21.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "investments",
        PriceRegistration: 94.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 145.0,
        PriceTransfer: 94.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "io",
        PriceRegistration: 39.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 39.0,
        PriceTransfer: 39.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "irish",
        PriceRegistration: 36.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 89.0,
        PriceTransfer: 36.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "it",
        PriceRegistration: 15.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 15.0,
        PriceTransfer: 15.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "jewelry",
        PriceRegistration: 51.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 108.0,
        PriceTransfer: 51.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "jp",
        PriceRegistration: 90.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 94.0,
        PriceTransfer: 90.0,
        TransferTerm: "No change",
    },
    {
        TLD: "juegos",
        PriceRegistration: 13.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: null,
        PriceTransfer: null,
        TransferTerm: "Not supported",
    },
    {
        TLD: "kaufen",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "kim",
        PriceRegistration: 15.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 69.0,
        PriceTransfer: 15.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "kitchen",
        PriceRegistration: 46.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 46.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "kiwi",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 74.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "land",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "lease",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "legal",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "lgbt",
        PriceRegistration: 43.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 55.0,
        PriceTransfer: 43.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "life",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "lighting",
        PriceRegistration: 21.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 21.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "limited",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "limo",
        PriceRegistration: 50.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 50.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "link",
        PriceRegistration: 5.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 51.0,
        PriceTransfer: 10.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "live",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 82.0,
        PriceTransfer: 25.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "loan",
        PriceRegistration: 31.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 89.0,
        PriceTransfer: 31.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "loans",
        PriceRegistration: 94.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 145.0,
        PriceTransfer: 94.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "lol",
        PriceRegistration: 16.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 74.0,
        PriceTransfer: 31.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "maison",
        PriceRegistration: 49.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 49.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "management",
        PriceRegistration: 21.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 21.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "marketing",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "mba",
        PriceRegistration: 31.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 89.0,
        PriceTransfer: 31.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "me",
        PriceRegistration: 17.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 47.0,
        PriceTransfer: 17.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "me.uk",
        PriceRegistration: 8.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 8.0,
        PriceTransfer: 0.0,
        TransferTerm: "No change",
    },
    {
        TLD: "media",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "memorial",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "mobi",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 12.0,
        PriceRestoration: 70.0,
        PriceTransfer: 12.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "moda",
        PriceRegistration: 22.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 22.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "money",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "mortgage",
        PriceRegistration: 43.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 96.0,
        PriceTransfer: 43.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "movie",
        PriceRegistration: 306.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 355.0,
        PriceTransfer: 306.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "mx",
        PriceRegistration: 34.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 67.0,
        PriceTransfer: 34.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "name",
        PriceRegistration: 9.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 64.0,
        PriceTransfer: 9.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "net",
        PriceRegistration: 11.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 67.0,
        PriceTransfer: 11.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "net.au",
        PriceRegistration: 15.0,
        PriceChangeOwnership: 40.0,
        PriceRestoration: 15.0,
        PriceTransfer: 0.0,
        TransferTerm: "No change",
    },
    {
        TLD: "net.nz",
        PriceRegistration: 24.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 24.0,
        PriceTransfer: 24.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "network",
        PriceRegistration: 19.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 19.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "news",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 82.0,
        PriceTransfer: 25.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "ninja",
        PriceRegistration: 18.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 72.0,
        PriceTransfer: 18.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "nl",
        PriceRegistration: 10.0,
        PriceChangeOwnership: 10.0,
        PriceRestoration: 10.0,
        PriceTransfer: 10.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "onl",
        PriceRegistration: 15.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 15.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "online",
        PriceRegistration: 39.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 126.0,
        PriceTransfer: 39.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "org",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 69.0,
        PriceTransfer: 12.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "org.nz",
        PriceRegistration: 24.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 24.0,
        PriceTransfer: 24.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "org.uk",
        PriceRegistration: 9.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 9.0,
        PriceTransfer: 0.0,
        TransferTerm: "No change",
    },
    {
        TLD: "partners",
        PriceRegistration: 49.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 49.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "parts",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "photo",
        PriceRegistration: 16.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 69.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "photography",
        PriceRegistration: 21.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 21.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "photos",
        PriceRegistration: 21.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 59.0,
        PriceTransfer: 21.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "pics",
        PriceRegistration: 16.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 60.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "pictures",
        PriceRegistration: 10.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 65.0,
        PriceTransfer: 10.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "pink",
        PriceRegistration: 15.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 69.0,
        PriceTransfer: 15.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "pizza",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "place",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "plumbing",
        PriceRegistration: 46.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 46.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "plus",
        PriceRegistration: 31.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 89.0,
        PriceTransfer: 31.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "poker",
        PriceRegistration: 43.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 96.0,
        PriceTransfer: 43.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "porn",
        PriceRegistration: 100.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 160.0,
        PriceTransfer: 100.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "pro",
        PriceRegistration: 14.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 69.0,
        PriceTransfer: 14.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "productions",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "properties",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "property",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: null,
        PriceTransfer: null,
        TransferTerm: "Not supported",
    },
    {
        TLD: "pub",
        PriceRegistration: 22.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 22.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "qa",
        PriceRegistration: 64.0,
        PriceChangeOwnership: 64.0,
        PriceRestoration: null,
        PriceTransfer: null,
        TransferTerm: "Not supported",
    },
    {
        TLD: "qpon",
        PriceRegistration: 15.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 69.0,
        PriceTransfer: 15.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "recipes",
        PriceRegistration: 35.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 35.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "red",
        PriceRegistration: 15.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 69.0,
        PriceTransfer: 15.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "reise",
        PriceRegistration: 101.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 157.0,
        PriceTransfer: 101.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "reisen",
        PriceRegistration: 19.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 19.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "rentals",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "repair",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "report",
        PriceRegistration: 19.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 19.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "republican",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "restaurant",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "reviews",
        PriceRegistration: 22.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 76.0,
        PriceTransfer: 22.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "rip",
        PriceRegistration: 17.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 72.0,
        PriceTransfer: 17.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "rocks",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 66.0,
        PriceTransfer: 12.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "ru",
        PriceRegistration: 36.0,
        PriceChangeOwnership: 36.0,
        PriceRestoration: null,
        PriceTransfer: null,
        TransferTerm: "Not supported",
    },
    {
        TLD: "ruhr",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 226.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "run",
        PriceRegistration: 20.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 79.0,
        PriceTransfer: 20.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "sale",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "sarl",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "school",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "schule",
        PriceRegistration: 19.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 19.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "se",
        PriceRegistration: 23.0,
        PriceChangeOwnership: 23.0,
        PriceRestoration: 23.0,
        PriceTransfer: 0.0,
        TransferTerm: "No change",
    },
    {
        TLD: "services",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "sex",
        PriceRegistration: 100.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 160.0,
        PriceTransfer: 100.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "sexy",
        PriceRegistration: 16.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 95.0,
        PriceTransfer: 65.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "sg",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 47.0,
        PriceRestoration: null,
        PriceTransfer: null,
        TransferTerm: "Not supported",
    },
    {
        TLD: "sh",
        PriceRegistration: 48.0,
        PriceChangeOwnership: 48.0,
        PriceRestoration: 48.0,
        PriceTransfer: 0.0,
        TransferTerm: "No change",
    },
    {
        TLD: "shiksha",
        PriceRegistration: 16.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 69.0,
        PriceTransfer: 16.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "shoes",
        PriceRegistration: 46.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 46.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "show",
        PriceRegistration: 31.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 89.0,
        PriceTransfer: 31.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "singles",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "soccer",
        PriceRegistration: 20.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 79.0,
        PriceTransfer: 20.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "social",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "solar",
        PriceRegistration: 46.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 46.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "solutions",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 20.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "studio",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 82.0,
        PriceTransfer: 25.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "style",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "sucks",
        PriceRegistration: 282.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 313.0,
        PriceTransfer: 282.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "supplies",
        PriceRegistration: 19.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 19.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "supply",
        PriceRegistration: 19.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 19.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "support",
        PriceRegistration: 21.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 21.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "surgery",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "systems",
        PriceRegistration: 21.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 21.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "tattoo",
        PriceRegistration: 16.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 75.0,
        PriceTransfer: 45.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "tax",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "taxi",
        PriceRegistration: 51.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 108.0,
        PriceTransfer: 51.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "team",
        PriceRegistration: 31.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 89.0,
        PriceTransfer: 31.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "technology",
        PriceRegistration: 21.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 21.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "tennis",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "theater",
        PriceRegistration: 51.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 108.0,
        PriceTransfer: 51.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "tienda",
        PriceRegistration: 50.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 50.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "tips",
        PriceRegistration: 21.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 59.0,
        PriceTransfer: 21.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "tires",
        PriceRegistration: 94.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 145.0,
        PriceTransfer: 94.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "today",
        PriceRegistration: 21.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 73.0,
        PriceTransfer: 21.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "tools",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "tours",
        PriceRegistration: 51.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 108.0,
        PriceTransfer: 51.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "town",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "toys",
        PriceRegistration: 46.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 46.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "trade",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "training",
        PriceRegistration: 27.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 27.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "tv",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 89.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "uk",
        PriceRegistration: 9.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 9.0,
        PriceTransfer: 0.0,
        TransferTerm: "No change",
    },
    {
        TLD: "university",
        PriceRegistration: 47.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 47.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "uno",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 69.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "us",
        PriceRegistration: 15.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 64.0,
        PriceTransfer: 15.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "vacations",
        PriceRegistration: 35.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 35.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "vc",
        PriceRegistration: 33.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 137.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "vegas",
        PriceRegistration: 57.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 110.0,
        PriceTransfer: 57.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "ventures",
        PriceRegistration: 35.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 35.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "vg",
        PriceRegistration: 35.0,
        PriceChangeOwnership: 35.0,
        PriceRestoration: 96.0,
        PriceTransfer: 35.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "viajes",
        PriceRegistration: 49.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 49.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "video",
        PriceRegistration: 22.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 76.0,
        PriceTransfer: 22.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "villas",
        PriceRegistration: 35.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 35.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "vision",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "voyage",
        PriceRegistration: 50.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 100.0,
        PriceTransfer: 50.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "watch",
        PriceRegistration: 37.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 37.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "website",
        PriceRegistration: 23.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 78.0,
        PriceTransfer: 23.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "wien",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 102.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "wiki",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 88.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "works",
        PriceRegistration: 30.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "world",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 30.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "wtf",
        PriceRegistration: 29.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 29.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "xyz",
        PriceRegistration: 12.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 80.0,
        PriceTransfer: 12.0,
        TransferTerm: "Renewed with transfer",
    },
    {
        TLD: "zone",
        PriceRegistration: 32.0,
        PriceChangeOwnership: 0.0,
        PriceRestoration: 83.0,
        PriceTransfer: 32.0,
        TransferTerm: "Renewed with transfer",
    },
];

export const tldMap = new Map<string, TLDPrice>();
{
    tldTable.forEach((item) => {
        tldMap.set(item.TLD, item);
    });
}
